### ISSUE TITLE
KeyError: '1.1' When running more than one device

### ISSUE THREAD

**Issue by nginnever** [mbevand/silentarmy#7]
Thanks for the updated miner. Looks simple and great.

Amdgpu-pro rx480's selecting

``./silentarmy --use 0,1``
```
Task exception was never retrieved
future: <Task finished coro=<Silentarmy.show_stats() done, defined at ./silentarmy:183> exception=KeyError('1.1',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "./silentarmy", line 231, in show_stats
    rate_gpus = sorted(gpus(last_sols, last_times, period_gpu))
  File "./silentarmy", line 193, in gpus
    sols[devid] = last_sols[0][devid] - last_sols[idx][devid]
KeyError: '1.1'
```

Selecting one device works well.

**Comment by mbevand** [comment]
It's a minor bug that causes the stats coroutine to crash. Does this fix it?:
https://github.com/mbevand/silentarmy/commit/c6851571e159e9aa952c76dbeb5bca9890a51e30

**Comment by mbevand** [comment]
Yes, it fixes it.
