### ISSUE TITLE
Cannot get OpenCL platforms (-1001)

### ISSUE THREAD

**Issue by chenqp7** [mbevand/silentarmy#91]
Follow the #63, I still can't get through. (The optimized files can't found any more)
I get 'Cannot get OpenCL platforms (-1001)', when './silentarmy --list'

##############################################
Connecting to stratum-zec.antpool.com:8899
Solver 2.0: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 2.1: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 2.2: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 3.0: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 3.1: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 3.2: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 4.0: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 4.1: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 4.2: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 5.0: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 5.1: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 5.2: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 6.0: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 6.1: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 6.2: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 7.0: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 7.1: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Solver 7.2: unexpected banner "/home/trumpchen/chen/silentarmy-master/sa-solver: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/trumpchen/chen/silentarmy-master/sa-solver)"
Task exception was never retrieved
future: <Task finished coro=<start_solvers() done, defined at ./silentarmy:307> exception=ProcessLookupError(3, 'No such process')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "./silentarmy", line 336, in start_solvers
    proc.kill()
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 127, in kill
    self._transport.kill()
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 142, in kill
    self._proc.kill()
  File "/usr/lib/python3.4/subprocess.py", line 1691, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Stratum server sent us the first job
Mining on 6 devices
################################################################

The system is ubuntu 14.04, with Nvidia GPU, Cuda 7.5 (have tried 8.0).

It never success, and make test is failed.

Could anyone help me with this? Thank you so much!

**Comment by chenqp7** [comment]
I figure out that the Cuda Driver version is not fit the Cuda Toolkit 8.0. Upgrade the driver fix the problem.
